version: '4'

services:
  mongodb:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=waiterdata
    restart: always
    ports:
      - "27017:27017"